### ISSUE TITLE
RFC: Easter Island map highlights two islands?

### ISSUE THREAD

**Issue by JohnHBrock** [axelboc/anki-ultimate-geography#117]
I noticed [the map for Easter Island](https://github.com/axelboc/anki-ultimate-geography/blob/f20e29fa30c82392bcf84af952240422cc1bdd5e/src/media/ug-map-easter_island.png) highlights two islands: Easter Island itself, as well as Isla Salas y Gómez (https://en.wikipedia.org/wiki/Isla_Salas_y_G%C3%B3mez). I can't find a reason to highlight both for the Easter Island entry, other than that both islands are owned by Chile. Seems like it should just be Easter Island on the map.

Any objections?

**Comment by axelboc** [comment]
Very true!

**Comment by aplaice** [comment]
FWIW, I've edited the old map to create [a version without Isla Salas y Gómez highlighted](https://commons.wikimedia.org/wiki/File:Easter_Island_in_its_region_(excluding_Isla_Salas_y_G%C3%B3mez).svg). (Uploaded to wikimedia for better global re-usability.) If that looks OK I can update `ug-map-easter_island.png` accordingly.

\<bicycle-shedding\>
However, on second thoughts, I'm slightly wavering on whether I think that the map should be updated. Administratively, Easter Island is part of the Easter Island commune and province, both of which include the uninhabited Isla Salas y Gómez. I don't think there is an administrative unit that consists of just Easter Island. 

Obviously, there's no reason we have to limit ourselves to administrative units as opposed to natural ones. 

OTOH, for Zanzibar, for example, we use the semi-autonomous region, which mainly consists of the islands Pemba and Unuja (colloquially called Zanzibar) rather than have separate cards for the two natural islands. For the Virgin Islands, we don't treat the entire island chain as a unit, but split it along political boundaries.

Using administrative, rather than natural, units is usually important because we also associate them with flags (which are obviously political, not natural). However, in the case of Easter Island, the situation is muddied by the fact that the flag is [not actually official](https://es.wikipedia.org/wiki/Bandera_de_Rapa_Nui) (English Wikipedia wasn't helpful)... (Some speculation in English [here](https://web.archive.org/web/20110823091946/http://www.nava.org/Flag%20Information/articles/reimiro/reimiro.htm) and [here](https://fotw.info/flags/cl-ip.html).)

By our previous convention of following English Wikipedia articles we should update the map to highlight only Easter Island, since in the [Easter Island article](https://en.wikipedia.org/wiki/Easter_Island) they only display maps of Easter Island itself. (Looking at Wikipedia in some other languages might have given different answers, though...)

\<\/bicycle-shedding\>

**Comment by axelboc** [comment]
**Reasons for keeping both islands highlighted**

- We mention that it's a special territory of Chile in the _Country info_ field.
- The special territory does include both islands.
- We highlight whole administrative areas on other maps.

**Reasons for not highlighting both islands**

- Easter Island is singular, so highlighting two islands is confusing.
- We mention that it's a Polynesian island (singular) in the _Country info_ field, so it's clear what we're talking about.
- Easter Island is renowned world-wide as the one island.
- Isla Salas y Gómez is uninhabited.
- With the two islands highlighted, there's no way to tell which is which.

The goal here is clearly to learn the location of Easter Island, as in the actual island, not the administrative area, so I agree that the uninhabited island should not be highlighted.

Your version looks great, @aplaice, please do update it.
