### ISSUE TITLE
British Indican Ocean Territory in German deck has London as capital

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#127]
London is indeed marked as the capital on the [German Wikipedia page](https://de.wikipedia.org/wiki/Britisches_Territorium_im_Indischen_Ozean), but this means the territory cannot be guessed from its capital (as it could very well be the UK or England).

We could add a hint, but I don't think we should keep London as the capital. It's the only overseas territory of the UK that has London as its capital in the German deck, so it's not coherent.

I see two ways to fix this:

1. Remove the capital from the _Capital:de_ field.
2. Follow the English Wikipedia page and change the capital to _Camp Justice_ (or its German translation, which I can't find on Wikipedia).

**Comment by Erim24** [comment]
That is something I think about everytime it shows up when I'm learning.
I have to main points:

1. The general rule is to follow the wikipedia article in the respective language, so according to that it should stay London and get a hint
2. The german wikipedia article doesn't define a capital per se but where the government(?) is located, that would argue for the removal of the capital. However, as far as I remember the same info was used in other cases.

So all in all, I would vote for adding a hint instead of removing the capital

**Comment by axelboc** [comment]
I've added the hint, plus a second one for London as the capital of _England_, which was also missing. Let me know if the hints are okay. 😉

**Comment by Erim24** [comment]
Seems good :D
