### ISSUE TITLE
Vectorized ocean maps

### ISSUE THREAD

**Issue by NathanaelRea** [axelboc/anki-ultimate-geography#136]
I noticed that most ocean and sea maps were low quality, and wanted to see if I could help. The oceanic maps seem to already be on Wikipedia except Polynesia, and so I added them to my fork, which your can see here (still need to adjust colors for consistency):
https://github.com/axelboc/anki-ultimate-geography/compare/master...OldOxygen:vector-maps

I would like to vector all the other ocean maps, but had some questions.
- Currently, the only svg files in the media directory are flags, why is this? Is it because it is suppose to be that way, or that nobody has vectored them yet?
- For each svg file, there is an associated exported png file. Are the vector files required to be exported for some reason?
- The oceanic svg files I added are around 110KB each, which is relatively large. Is this a problem?

**Comment by axelboc** [comment]
Hi there! 👋 Thanks for offering to help out. 🥇 Sorry I took so long to get back to you.

The maps of the sub-regions of Oceania you found on Wikimedia and tweaked to remove labels are amazing, thank you! If you open a PR that I can modify, I'll do the necessary work to convert them to 500px-wide PNGs, optimise them with [TinyPNG](https://tinypng.com/) and add them to the `sources.csv` document (unless you'd like to do all this yourself! 😄). 

---

The reason most maps are in PNG format is for **file size**. I want to keep the deck as small as possible so it can be synced quickly, and stored on low-end smartphones. The limit for SVG files is currently **50 kB** after [SVGO](https://jakearchibald.github.io/svgomg/) optimisation. Anything below this has to be converted to PNG and then optimised again. For this reason, **vectorization is not an end goal in itself for this deck**. Vecotrization is, however, a necessary step to achieve **visual consistency** between all of the maps. Before you jump into it, though, let me fill you in on where we're up to.

The current maps of oceans, seas and water bodies (gulf, bays, lakes, etc.) suffer from two major problems: quality and consistency.

- In terms of quality, the maps are neither accurate nor up to date, and their sources are [mostly unknown](https://github.com/axelboc/anki-ultimate-geography/issues/2#issuecomment-513472371). This means that we can't vectorize them directly. We have to turn to more up-to-date maps on Wikipedia. As an example, nowadays the [Aral Sea](https://en.wikipedia.org/wiki/Aral_Sea) is no way near as big as it is [pictured in the deck](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-aral_sea.jpg).
- In terms of consistency, the maps look nothing like most of the other maps in the deck, which follow the [style guide](https://commons.wikimedia.org/wiki/File:Toolbox_SVG_locator_maps_(location_map_based)-en.svg) of the [SVG locator map project](https://commons.wikimedia.org/wiki/Category:SVG_locator_maps_(16:9_regional_location_map_scheme)). Unfortunately, the locator map style guide does not take into consideration water bodies. @aplaice did come up with a very nice style for inland seas when he made the maps for the [Dead Sea](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-dead_sea.png) and the [Sea of Galile](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-sea_of_galilee.png), so it's a good place to start from. However, other types of water bodies, like gulfs, might not as easy to delimit, and the borders of many seas are highly contested. We would need a way to represent contested areas (like for sovereign states), and perhaps even areas the water bodies have shrunk or expanded by in recent times (e.g. for the Aral Sea).

All in all, updating the maps of the water bodies is going to take a whole lot of work... So you're help is more than welcome!! 😊 If I didn't scare you away and you want to get your hands dirty, I'd say a good way to start would be to pick a well-delimited water body (e.g. like the Black Sea). Once you've picked one, find the SVG source file of an existing 16/9 country locator map at the same zoom level as the sea (check out `sources.csv`), modify it to put the water body in the center and to highlight it, and then show us the result!

**Comment by aplaice** [comment]
## IHO

> Some types of water bodies, like gulfs, might not be easy to delimit, and the borders of many seas are highly contested.

In terms of defining the exact extent of the water bodies, I think that the best source would be the IHO's ([International Hydrographic Organisation](https://en.wikipedia.org/wiki/International_Hydrographic_Organization)'s) 1953 *Limits of Oceans and Seas, 3rd edition*. It seems to be what Wikipedia uses for the purpose (for example, see the articles on the [Norwegian sea](https://en.wikipedia.org/wiki/Norwegian_Sea#Extent) or the [Celtic sea](https://en.wikipedia.org/wiki/Celtic_Sea#Limits)). There's a PDF of the report on the [IHO's own website](http://www.iho.int/iho_pubs/standard/S-23/S-23_Ed3_1953_EN.pdf), an OCRed (but, other than an additional final 3 pages, identical) version [here](https://epic.awi.de/id/eprint/29772/1/IHO1953a.pdf) and a representation of the data in machine-readable form [here](https://doi.pangaea.de/10.1594/PANGAEA.777975). Alternatively, the [4th edition draft](https://www.iho.int/mtg_docs/com_wg/S-23WG/S-23WG_Misc/Draft_2002/Draft_2002.htm) might be used instead — I have no idea how, or whether it differs significantly from the 3rd edition.

There's a global SVG map purporting to represent the IHO data on the commons [here](https://commons.wikimedia.org/wiki/File:Oceans_and_seas_boundaries_map-en.svg), but unfortunately, while it's thorough and detailed, it doesn't really fit our conventions, and it seems to have a couple of errors (for instance, in it, the Celtic Sea doesn't have a western border, even though the IHO does specify one, and the eastern border also doesn't seem right). I can't find anything that's particularly better, though.

## Question marks?

In terms of conventions and styles for the UG maps, currently we have two main conventions:
having a question mark within some of the more "open" seas, and a highlighting of the extent of the water body, for some of the more "enclosed" ones. 

Do we ideally want to switch to the latter style for all the water body maps, or is the current split desirable? (i.e. for the maps that currently have a question mark placed within the sea, rather than a highlight of the sea, do we want to (aim to) replace them with maps with a question mark, or ones with the extent of the sea highlighted?)

**Comment by axelboc** [comment]
> Do we ideally want to switch to the latter style for all the water body maps, or is the current split desirable?

My vote goes to highlighting. 🔆
