### ISSUE TITLE
Is there a path to upgrade from v1.0?

### ISSUE THREAD

**Issue by ElChapitan** [axelboc/anki-ultimate-geography#16]
Really, I'll take just about any path, even if it is difficult.  I'd prefer not to have to start the process over, even though i'd get a lot of quick wins  :-)

**Comment by axelboc** [comment]
I know the feeling 😞 

I'm afraid there's no solution but to start fresh. Personally, I found it quite satisfying to relearn everything from scratch with nice-looking flags and maps.

**Comment by ElChapitan** [comment]
<sigh>

OK.  Next question.  Do you plan on having another breaking change anytime soon?

**Comment by axelboc** [comment]
Oh no, not at all. @code-hunger is working on adding more interesting snippets of country information, but this won't require any changes to the templates and fields. However, I did have issues with importing the deck in the past (i.e. updating to a minor version, or even just re-importing the same version)... I even lost my progress once. Not sure if it was just me, though: if you have time, please, would you mind importing the latest version, using it for a couple of days, re-importing it and letting me know what happens to your progress?

**Comment by ElChapitan** [comment]
No problem, but I also would like to know... what's the upgrade path?

**Comment by axelboc** [comment]
Hmm well you can either download the apkg file from the [releases page](https://github.com/axelboc/anki-ultimate-geography/releases) and just open it, or you can clone or download this repo and import the _Ultimate_Geography_ folder with the [CrowdAnki](https://github.com/Stvad/CrowdAnki) add-on. (Note that you won't be able to use the add-on's GitHub import feature because of the way I structured the repo.)

**Comment by axelboc** [comment]
FYI, I've just added an [_Upgrading_ section](https://github.com/axelboc/anki-ultimate-geography#upgrading) to the README with some clear steps. This won't work for migrating from v1.0 to v2.x, though, as discussed.
