### ISSUE TITLE
Replace single quotes with apostrophes

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#167]
Very minor, but it would be nice to replace all the single quotes `'` with proper apostrophes `’`, in `data.csv` and in various files (README, etc.)

_Waiting for the Spanish translation to be completed (#161) to avoid conflicts._

**Comment by josealberto4444** [comment]
Don't worry about the conflicts. As we don't use apostrophes in Spanish, you can update the rest without problem for me, I am rebasing my branch every time before working on the translation. You can go ahead. =)

**Comment by ukanuk** [comment]
Note that simply replacing eveything with `‘` or `’` isn't fully correct. Nukuʻalofa for example uses `ʻ`, an [okina](https://en.wikipedia.org/wiki/ʻOkina) encoded under U+02BB (modifier letter turned comma). 

Also note that in the current version of Anki, this makes searching for such country significantly more difficult since typing `'` into the search box does not automatically match the proper `‘`, `’`, or `ʻ`. Other software does match these characters when searching, so I've opened an Anki ticket about it. It'll be interesting to see how they respond: https://anki.tenderapp.com/discussions/ankidesktop/38066-searching-for-smart-quotes-typogragraphers-quotes-curly-quotes-apostrophes

**Comment by axelboc** [comment]
Interesting, re. Nuku'alofa!

Given all this, and the fact that introducing typographic apostrophes adds a bit more complexity to the contribution process, do you think we shouldn't bother?

**Comment by ukanuk** [comment]
For now, I don't think the change is worth it.

This is almost purely a visual change, proper typography everywhere possible makes reading easier with apostrophes versus straight quotes, and in some cases like Nuku'alofa is additionally culturally correct.

I'm not concerned about the added complexity for contributors - if they added a name without the proper quotes, it's easily fixed or easily ignored.

Of course I really like using proper typography everywhere possible. But the lost search functionality is a huge problem to me, when most people don't immediately notice the difference among quotes and won't understand why their cards aren't showing up in the card browser and in filtered decks.

If Anki ever fixes the search thing, then at that point I'd say we should implement proper typography. But it sounds like this is super low priority right now, and may never be implemented. It would also have to be tested in ankidroid and fixed there if needed as well.

If the deck ever gets scripts to automatically update place names, that would make it really easy to switch between smart quotes and straight quotes, since iirc Wikipedia uses the typographically correct smart versions.

**Comment by axelboc** [comment]
Alright, I agree. Let's close this for now, then 👍
