### ISSUE TITLE
Make hints consistent

### ISSUE THREAD

**Issue by horwitz** [axelboc/anki-ultimate-geography#179]
Half of the 10 hints area already simply the entity's polity—this issue suggests making all 10 of the same form, specifically:

```
Country               | Capital     | Capital hint (OLD)      | Capital hint (NEW)
----------------------+-------------+-------------------------+---------------------
Guadeloupe            | Basse-Terre | Not a sovereign country | Overseas department
Saint Kitts and Nevis | Basseterre  | Sovereign country       | Sovereign country
Cayman Islands        | George Town | Two-word country name   | Overseas territory
Guyana                | Georgetown  | One-word country name   | Sovereign country
Jamaica               | Kingston    | Caribbean               | Sovereign country
Norfolk Island        | Kingston    | Oceania                 | External territory
England               | London      | Constituent country     | Constituent country
United Kingdom        | London      | Sovereign country       | Sovereign country
Aruba                 | Oranjestad  | Constituent country     | Constituent country
Sint Eustatius        | Oranjestad  | Special municipality    | Special municipality
```

(The table above only covers the English version, of course.)

**Comment by axelboc** [comment]
It did cross my mind when I reviewed the French translation. Makes sense to me 👍

**Comment by axelboc** [comment]
@aplaice raises [some very good points](https://github.com/axelboc/anki-ultimate-geography/pull/190#issuecomment-560491513). I agree that "Sovereign Country"/"Not a sovereign country" reveals less information than the exact polity. I wish there were a simpler term we could use instead of "Not a sovereign country", but there doesn't seem to be...

Another option I thought of after reading @aplaice's comment was to have hints of the form: _Two cards share this capital_, thus inviting the user to name both. The problem is that _Basse-Terre_ and _Basseterre_, as well as _George Town_ and _Georgetown_ aren't spelt the same, and naming both cards would not help knowing which capital belongs to which... So it would only really work for Kingston, London and Oranjestad.

All in all, I suggest only replacing the hints for _Georgetown_/_George Town_ and _Kingston_ with "Sovereign Country"/"Not a sovereign country" as @aplaice suggested in #190.

**Comment by horwitz** [comment]
What about London, England, going from "Constituent country" to "Not a sovereign country" (and London, United Kingdom, staying as "Sovereign country")?

Currently:
London, England = "Constituent country"
London, United Kingdom = "Sovereign country"

**Comment by aplaice** [comment]
> What about London, England, going from "Constituent country" to "Not a sovereign country" (and London, United Kingdom, staying as "Sovereign country")?

Yes, that totally works! (In my [comment on the pull request](https://github.com/axelboc/anki-ultimate-geography/pull/190#issuecomment-560491513), I had mistakenly written that London formed a triad (England/UK/British Indian Ocean Territory), but that's only the case in the French and German versions of the decks, not the main/English one. Sorry for the terrible brain-fart!)

**Comment by horwitz** [comment]
Excellent—I've updated #190 to have the capital hints changed for 5 "country"s (including England).

Any reason the FR and DE decks have a different capital for BIOT than the EN and NB decks?

**Comment by aplaice** [comment]
It's because the German Wikipedia article for the BIOT lists London as its capital:

https://de.wikipedia.org/wiki/Britisches_Territorium_im_Indischen_Ozean

As for the French deck, I'm not actually sure — the French Wikipedia article lists the BIOT as having no capital:

https://fr.wikipedia.org/wiki/Territoire_britannique_de_l%27oc%C3%A9an_Indien

**Comment by axelboc** [comment]
I'm on board with removing the capital for BIOT in French. This means the hint can go as well, since it's only used on the country/capital templates. I'll open a separate issue, though.
