### ISSUE TITLE
Add content guidelines for country names

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#181]
From time to time, we get a request about changing the name of a country in the deck in a way that doesn't match the title of the country's article on Wikipedia (e.g. #180).

It would be convenient to have a section in [CONTRIBUTING.md](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#content-guidelines) to which we could point people to explain our stance on this (i.e. follow Wikipedia) and the reasoning behind it.

**Comment by mighty-cthulhu** [comment]
Why not use more authoritative sources like 
https://www.state.gov/independent-states-in-the-world/
or
https://www.cia.gov/library/publications/resources/the-world-factbook/

**Comment by aplaice** [comment]
One slight complication with our (IMO sensible) policy of using Wikipedia as a source, is that Wikipedia is obviously editable.

This can be an advantage in situations where Wikipedia is wrong, but being able to edit the source can also easily lead to tricky, delicate situations.

Hence it might, perhaps, be worth having some general policy for (non-obvious\*) edits to Wikipedia, by contributors here. Would, say, waiting a while before pulling in a change (to allow for review/reversion) be sensible?

\* an obvious edit might be the capital of a country changing due to some presumably well-known political decision and the article being updated to reflect that.

**Comment by aplaice** [comment]
As for more authoritative sources:

I think that relying on an encyclopaedia, rather than directly on a primary source is sensible. 

The main issue is that there are often doubts as to what to choose as the right [name](https://github.com/axelboc/anki-ultimate-geography/issues/180#issuecomment-557793328), or [capital](https://github.com/axelboc/anki-ultimate-geography/issues/166), or [flag](https://github.com/axelboc/anki-ultimate-geography/issues/111), or map. It might not be non-obvious which option is the best. Primary sources might disagree with each other.

The editors of the encyclopaedia will usually have already considered these problems while writing and editing their articles, and will have reached some sort of conclusion.

The advantage of relying on their judgement is that:

1. In such an encyclopaedia article the topic will have been considered by more people or better-qualified people, than will be available here.

2. It avoids having flamewars here. :)

Using Wikipedia, rather than another encyclopaedia, is reasonable IMO, because:

1. It's probably at least as good as its competitors.

2. Its free/libre/collaborative nature is a good cultural fit.

3. It allows people who have a strong opinion on a given choice to argue in favour of their preferred alternative and possibly ultimately change the choice, while keeping the discussion to a venue arguably more suitable than this repo.

FWIW in the case of East Timor, Britannica [agrees](https://www.britannica.com/place/East-Timor) with Wikipedia, though it [doesn't agree](https://www.britannica.com/place/Cote-dIvoire) in the case of Côte d'Ivoire.

**Comment by mighty-cthulhu** [comment]
By sticking to the old names of the countries that still linger in Wikipedia this deck propagates incorrect information,  just to stick to one primary source out of principle. If a country declares its new name in English and official organization adopt it, why hold on to the incorrect version?

In case of Timor-Leste even Wikipedia says that:

> The official names under the Constitution are Democratic Republic of Timor-Leste in English [...]. The International Organization for Standardization (ISO) official short form in English and all other languages is Timor-Leste (codes: TLS & TL), which has been adopted by the United Nations,[18] the European Union,[19] and the national standards organisations of France (AFNOR), the United States (ANSI),[20] United Kingdom (BSI), Germany (DIN), and Sweden (SIS), all diplomatic missions to the country by protocol and the CIA World Factbook.

https://en.wikipedia.org/wiki/East_Timor#Etymology

Similarly, the names Czechia, Cabo Verde, and Côte d'Ivoire deserve to be used as the primary names in the deck with old versions mentioned as well.

**Comment by axelboc** [comment]
Again, it comes down to Wikipedia's guideline of "most common usage". We've decided to follow this guideline here for simplicity. I understand that this is not ideal, so perhaps there's something we can do to mitigate the issue.

I don't believe that putting the name in parentheses, like _Ivory Coast (Côte d'Ivoire)_ or _Côte d'Ivoire (Ivory Coast)_ is a good idea. This format is a leftover from the original v1 deck. It doesn't clarify anything.

How about instead of writing "Also known as ..." in the _Country info_ field, we just write "Officially known as ...", perhaps followed with a date, like "... since 2016"?

**Comment by ohare93** [comment]
> By sticking to the old names of the countries that still linger in Wikipedia this deck propagates incorrect information, just to stick to one primary source out of principle. If a country declares its new name in English and official organizations adopt it, why hold on to the incorrect version?

They are still in the Wikipedia because those names are still the most used. Ivory Coast may not what those of Côte d'Ivoire wish their country to be known as, but that does not make it "incorrect" because that's what everyone mainly still uses! :sweat_smile: 

We are arguing about names of things here, and things only have names when people call them that :thinking: so since most people call it "Ivory Coast", that's the most useful name.

> Why not use more authoritative sources like
> https://www.state.gov/independent-states-in-the-world/
> or
> https://www.cia.gov/library/publications/resources/the-world-factbook/

Simply because a the US state government (or any other bureaucratic body) agrees to officially use whatever name a country wants (because politics!) does not make it a more authoritative source. Their goal is good relations. This deck's goal is useful information.

Completely agree with @axelboc and @aplaice :+1:

**Comment by ukanuk** [comment]
For posterity, here's a source for the Wikipedia title being the most commonly used / commonly recognized name, even if the article itself happens to start with a commonly used name differing from the article title.

For example, the article [Republic of Artsakh](https://en.wikipedia.org/wiki/Republic_of_Artsakh) starts with "**Artsakh**, officially the **Republic of Artsakh** or the **Nagorno-Karabakh Republic** is a..." Despite *Artsakh* appearing to be the common name from the article text, the Wikipedia policy is that the article title is the most-used name. Therefore, the UG name should be *Republic of Artsakh* rather than just *Artsakh* (#294).

https://en.wikipedia.org/wiki/Wikipedia:Article_titles#Use_commonly_recognizable_names
>   . . . Some topics have multiple names, and some names have multiple topics: this can lead to disagreement about which name should be used for a given article's title. Wikipedia does not necessarily use the subject's "official" name as an article title; it generally prefers the name that is most commonly used (as determined by its prevalence in a significant majority of independent, reliable English-language sources). . . When there is no single, obvious name that is demonstrably the most frequently used for the topic by these sources, editors should reach a consensus as to which title is best by considering these criteria directly... The following are examples of the application of the concept of commonly used names in support of recognizability:
> . . .
> **Places**
> * Germany (not: Deutschland)
> * Great Pyramid of Giza (not: Pyramid of Khufu)
> * North Korea (not: Democratic People's Republic of Korea)
> * Westminster Abbey (not: Collegiate Church of Saint Peter at Westminster)
