### ISSUE TITLE
Check image licences

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#2]
- Audit licences.
- Make sure all images are under a sufficiently permissive licence (public domain, Creative Commons, etc.); replace the ones that aren't.
- Add section to `LICENSE.md` listing all image licences and attributions.

**Comment by axelboc** [comment]
All [sovereign state flags](https://en.wikipedia.org/wiki/Gallery_of_sovereign_state_flags) are Public Domain or CC0, except for https://commons.wikimedia.org/wiki/File:Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg

**Comment by axelboc** [comment]
Most of the maps are from the [locator maps project](https://commons.wikimedia.org/wiki/Category:SVG_locator_maps_(16:9_regional_location_map_scheme)) on [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page) and released under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) licence.

**Comment by axelboc** [comment]
**`LICENCE.md` updated.**

The licence of the following maps is unknown at this times:

- Maps of water bodies (oceans, seas, gulfs, etc.)
- Maps of Azores, Ceuta, Corsica, Galapagos Islands, Kaliningrad Oblast, Melanesia, Melilla, Micronesia, Polynesia, Sardinia, Sumatra and Zanzibar.

**Comment by aplaice** [comment]
Firstly, thank you for an amazing deck — finally after a couple of decades of life I've learned some geography\! :)

I've gone through the files whose provenance was uncertain (as listed in `LICENSE.md`), using google reverse image search and other methods, trying to find the sources.

# Table

This looked much better in a spreadsheet than it does here, so I'll summarise below the table.

|                                                                                                                                                       | License      | source                                                                                                               | comment on source                          | alternative                                                                                                                                                                       | comment on alternative / improvement                                   |
| ----------------------------------------------------------------------------------------------------------------------------------------------------- | ------------ | -------------------------------------------------------------------------------------------------------------------- | ------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [ug-map-adriatic\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-adriatic_sea.jpg)                | ?            | Template "A"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-aegean\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-aegean_sea.jpg)                    | ?            | Template "A"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-arabian\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-arabian_sea.jpg)                  | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-aral\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-aral_sea.jpg)                        | ?            | Template "C"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-arctic\_ocean.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-arctic_ocean.jpg)                | PD           | [source](https://commons.wikimedia.org/wiki/File:Arctic_Ocean_-_en.png)                                              | Text removed                               | [source1](https://commons.wikimedia.org/wiki/File:Arctic_Ocean.png)                                                                                                               | Doesn't have the line of longitude partially rubbed out.               |
| [ug-map-atlantic\_ocean.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-atlantic_ocean.jpg)            | PD           | [source](https://commons.wikimedia.org/wiki/File:Atlantic_Ocean_-_en.png)                                            | Text removed                               | [source1](https://commons.wikimedia.org/wiki/File:Atlantic_Ocean.png)                                                                                                             | Doesn't have the lines of longitude and latitude partially rubbed out. |
| [ug-map-azores.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-azores.jpg)                             | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Locator_map_of_Azores_in_EU.svg)                                    | Cropped                                    |                                                                                                                                                                                   |                                                                        |
| [ug-map-baltic\_sea.png](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-baltic_sea.png)                    | ?            | Template "D"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-bay\_of\_bengal.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-bay_of_bengal.jpg)             | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-bay\_of\_biscay.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-bay_of_biscay.jpg)             | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Bay_of_Biscay_map.png)                                              | Cropped, text removed, question mark added |                                                                                                                                                                                   |                                                                        |
| [ug-map-bering\_strait.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-bering_strait.jpg)              | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:East_Siberian_Sea_map.png)                                          | Cropped, text removed, question mark added |                                                                                                                                                                                   |                                                                        |
| [ug-map-black\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-black_sea.jpg)                      | ?            | Template "A"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-caribbean\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-caribbean_sea.jpg)              | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-caspian\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-caspian_sea.jpg)                  | ?            | Template "A2"                                                                                                        |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-celtic\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-celtic_sea.jpg)                    | PD           | [source](https://commons.wikimedia.org/wiki/File:Mappa_an_Mor_Keltek.png)                                            | Added white line on side                   |                                                                                                                                                                                   | could remove the white line                                            |
| [ug-map-ceuta.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-ceuta.jpg)                               | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Localizaci%C3%B3n_de_Ceuta.svg)                                     |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-coral\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-coral_sea.jpg)                      | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-corsica.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-corsica.jpg)                           | ?            | Template "E"                                                                                                         |                                            | [source1](https://commons.wikimedia.org/wiki/File:Europe_location_Corsica.png) [source2](https://commons.wikimedia.org/wiki/File:Corse_in_France.svg)                             |                                                                        |
| [ug-map-dead\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-dead_sea.jpg)                        | No license   | [source](http://s-wadsworth.cengage.com/religion_d/special_features/popups/maps/matthews_world/content/map_114.html) | Warren Matthews' "World Religions"         |                                                                                                                                                                                   |                                                                        |
| [ug-map-denmark\_strait.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-denmark_strait.jpg)            | PD           | [source](https://commons.wikimedia.org/wiki/File:Denemarkenstraat.PNG)                                               |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-east\_siberian\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-east_siberian_sea.jpg)     | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:East_Siberian_Sea_map.png)                                          | Cropped, text removed, question mark added |                                                                                                                                                                                   |                                                                        |
| [ug-map-english\_channel.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-english_channel.jpg)          | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Bay_of_Biscay_map.png)                                              | Cropped, text removed, question mark added |                                                                                                                                                                                   |                                                                        |
| [ug-map-galapagos\_islands.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-galapagos_islands.jpg)      | ?            |                                                                                                                      |                                            | [source1](https://commons.wikimedia.org/wiki/File:Galapagos_Islands_in_South_America_\(-mini_map_-rivers\).svg)                                                                   |                                                                        |
| [ug-map-gulf\_of\_california.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-gulf_of_california.jpg)   | ?            | Template "B2"                                                                                                        |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-gulf\_of\_carpentaria.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-gulf_of_carpentaria.jpg) | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-gulf\_of\_mexico.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-gulf_of_mexico.jpg)           | PD           | [source](https://commons.wikimedia.org/wiki/File:Gulf_of_Mexico_places.png)                                          | Retouched (orange spots removed)           | [source1](https://commons.wikimedia.org/wiki/File:GulfofMexico3D.jpg)                                                                                                             | Not necessary to manually remove the orange spots (possibly better)    |
| [ug-map-gulf\_of\_thailand.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-gulf_of_thailand.jpg)       | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-hudson\_bay.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-hudson_bay.jpg)                    | CC BY-SA 2.5 | [source](https://commons.wikimedia.org/wiki/File:Labradorseamap.png)                                                 | Text removed, question mark added          |                                                                                                                                                                                   |                                                                        |
| [ug-map-indian\_ocean.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-indian_ocean.jpg)                | PD           | [source](https://commons.wikimedia.org/wiki/File:Indianocean.PNG)                                                    |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-kaliningrad\_oblast.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-kaliningrad_oblast.jpg)    | ?            | Template "E"                                                                                                         |                                            | [source1](https://commons.wikimedia.org/wiki/File:Kaliningrad_Oblast_within_Europe.svg) [source2](https://commons.wikimedia.org/wiki/File:Map_of_Russia_-_Kaliningrad_Oblast.svg) |                                                                        |
| [ug-map-labrador\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-labrador_sea.jpg)                | CC BY-SA 2.5 | [source](https://commons.wikimedia.org/wiki/File:Labradorseamap.png)                                                 | Text removed, question mark added          |                                                                                                                                                                                   |                                                                        |
| [ug-map-mediterranean\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-mediterranean_sea.jpg)      | ?            | Template "F"                                                                                                         |                                            | [source1](https://commons.wikimedia.org/wiki/File:Mediterranean_Sea_location_map.svg)                                                                                             |                                                                        |
| [ug-map-melanesia.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-melanesia.jpg)                       | PD           | [source](https://commons.wikimedia.org/wiki/File:Map_OC-Melanesia.PNG)                                               | Text removed, old version\!                |                                                                                                                                                                                   |                                                                        |
| [ug-map-melilla.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-melilla.jpg)                           | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Localizaci%C3%B3n_de_Melilla.svg)                                   |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-micronesia.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-micronesia.jpg)                     | PD           | [source](https://commons.wikimedia.org/wiki/File:Map_of_Micronesia_Oceania.png)                                      |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-norwegian\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-norwegian_sea.jpg)              | No license   | [source](https://www.worldatlas.com/aatlas/infopage/norwegiansea.htm)                                                | see below                                  | [source1](https://commons.wikimedia.org/wiki/Category:Maps_of_the_Norwegian_Sea) [source2](https://commons.wikimedia.org/wiki/File:Norwegian_Sea_blank_map.png)                   | No great alternative                                                   |
| [ug-map-pacific\_ocean.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-pacific_ocean.jpg)              | PD           | [source](https://commons.wikimedia.org/wiki/File:Pacific_Ocean_-_en.png)                                             | Text removed                               | [source1](https://commons.wikimedia.org/wiki/File:Pacific_Ocean.png)                                                                                                              | Doesn't have the lines of longitude and latitude partially rubbed out. |
| [ug-map-persian\_gulf.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-persian_gulf.jpg)                | ?            | Template "F"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-philippine\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-philippine_sea.jpg)            | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-polynesia.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-polynesia.jpg)                       | CC BY 3.0    | [source](https://commons.wikimedia.org/wiki/File:Polynesian_triangle.svg)                                            | Old version                                |                                                                                                                                                                                   |                                                                        |
| [ug-map-red\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-red_sea.jpg)                          | ?            | Template "F"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-sardinia.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-sardinia.jpg)                         | ?            | Template "E"                                                                                                         |                                            | [source1](https://commons.wikimedia.org/wiki/File:Europe_location_Sardinia.png) [source2](https://commons.wikimedia.org/wiki/File:Sardinia_in_Italy.svg)                          |                                                                        |
| [ug-map-sea\_of\_galilee.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-sea_of_galilee.jpg)           | No license   | [source](http://s-wadsworth.cengage.com/religion_d/special_features/popups/maps/matthews_world/content/map_114.html) | Warren Matthews' "World Religions"         |                                                                                                                                                                                   |                                                                        |
| [ug-map-sea\_of\_japan.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-sea_of_japan.jpg)               | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-south\_china\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-south_china_sea.jpg)         | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-southern\_ocean.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-southern_ocean.jpg)            | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:Location_Southern_Ocean.svg)                                        |                                            |                                                                                                                                                                                   | Could generate PNG instead of JPG                                      |
| [ug-map-sumatra.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-sumatra.jpg)                           | CC BY-SA 2.5 | [source](https://commons.wikimedia.org/wiki/File:LocationSumatra.svg)                                                |                                            |                                                                                                                                                                                   | Could generate PNG instead of JPG                                      |
| [ug-map-tasman\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-tasman_sea.jpg)                    | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-white\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-white_sea.jpg)                      | CC BY-SA 3.0 | [source](https://commons.wikimedia.org/wiki/File:White_Sea_map.png)                                                  | Cropped, text removed, question mark added |                                                                                                                                                                                   |                                                                        |
| [ug-map-yellow\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-yellow_sea.jpg)                    | ?            | Template "B"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |
| [ug-map-zanzibar.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-zanzibar.jpg)                         | ?            | Template "G"                                                                                                         |                                            |                                                                                                                                                                                   |                                                                        |

## Definitely OK

Just under half of the files are definitely from wikimedia.

Some of them had been slightly retouched, particularly to remove the labels, as mentioned in the comments section. I'll update `LICENSE.md` accordingly.

(However, I'm not sure whether keeping the license and attribution information in an unstructured form in `LICENSE.md` is practical, and whether, say, having a `sources.csv` file with three or four fields for media filename, license, source and (perhaps) modifications, might not be better. GitHub seems to have a relatively nice CSV viewer, so such a file could even be quite readable out-of-the-box. Obviously, this is just a suggestion.)

Some of these files have very similar, but slightly better alternatives (e.g. in the Anki versions, some of the ocean maps have "rubbed out" lines of longitude and latitude, due to the removal of the text labels; the "alternative" versions don't have those disadvantages). I'm not sure if it's worth replacing the images with slight improvements if you're planning to completely overhaul them, but I'll open a pull request, just in case.

## Probably template-based — probably OK

Half of the files appear to be based on standard templates which might or might not be open source. However, I've been unable to find exact matches anywhere on the web.

I've grouped the files by different template "types", for tidiness and to help (possibly, in the long run) to bring consistency.

I've listed some alternatives for a few of these files, but I'm not sure whether there's a plan for introducing a unified "style" to the sea maps (in the same way that there's a unified style for the country maps, due to the use of the maps from the 16:9 regional location map scheme). One important question is whether the option with the sea being shaded or with a question mark in the middle of the sea, is preferred ([ug-map-aral\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-aral_sea.jpg) vs. [ug-map-bay\_of\_bengal.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-bay_of_bengal.jpg)). Should it depend on whether the sea is ["mediterranean"](https://en.wikipedia.org/wiki/Mediterranean_sea_\(oceanography\)) or not? This is probably material for another issue…

For islands there's the precedent of [Bali](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-bali.png) and [the Åland islands](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-aland_islands.png), though they have slightly different styles (highlighting the island and the rest of its country, but with different colours vs. only highlighting the island and treating the rest of its country like foreign countries).

## Dubious ([ug-map-galapagos\_islands.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-galapagos_islands.jpg))

<http://www.scribaepub.it/play.html?ebook=339&asset=1304> is the same image, but is probably not the original source. However, I can't find the map on wikimedia, and it doesn't look like a standard template-based map, so by default one should probably assume that the original wasn't "open source".

I'll open up a pull request with the most reasonable looking [potential replacement](https://commons.wikimedia.org/wiki/File:Galapagos_Islands_in_South_America_\(-mini_map_-rivers\).svg).

## Probably not OK

Three of the files (marked as "No license") seem not to be under a Creative Commons or compatible license.

### [ug-map-dead\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-dead_sea.jpg) and [ug-mapg-sea\_of\_galilee.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-sea_of_galilee.jpg)

It seems that they're based on the map from [here](http://s-wadsworth.cengage.com/religion_d/special_features/popups/maps/matthews_world/content/map_114.html), which is apparently taken from Warren Matthews' book "World Religions".

### [ug-map-norwegian\_sea.jpg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-norwegian_sea.jpg)

[World Atlas/Graphic maps](https://www.worldatlas.com/aatlas/infopage/norwegiansea.htm) (graphicsmaps.com redirects to worldatlas.com) appears to be the original source — the Anki deck version seems to be a cropped and "re-touched" version of it (e.g. look at Denmark for traces of the old labels).

I'll try to find and/or make an OK replacement for these three files. Given the problematic nature of the current versions, the bar for the replacement might perhaps not be too high.

**Comment by axelboc** [comment]
Wow, thanks a lot for this very thorough investigation! 🔎

First off, you're totally right, a `sources.csv` file will make it much simpler to list and maintain image licences and to keep track of modifications. Are you up to get this started right away, at least with the licences you added in your PR #103, or would you prefer I merge your PR for now?

On the topic of replacing images with better-licenced (and better-looking) ones, here are my thoughts:

- Let's go ahead and replace the ocean maps and the gulf of Mexico map. The ones you found are much cleaner, so no hesitation here.
- Happy with the Galapagos map that you found and modified. Since the licence is uncertain and you've already done the replacement, it's a no-brainer as well. One that looks more like a locator map (i.e. with a small map of the globe in the bottom left-hand corner) would be ideal, but that can be done as part of issue #1.
- The map of Polynesia can indeed be replaced with the latest version ... and may as well remove the labels and circles and leave only the triangle, I reckon.
- If there are other easy wins like these, please feel free to do the replacements.
- About the three seas you mention that are most likely not under a permissive licence, I'd be tempted to remove them from the deck altogether. to be honest.. After all, the deck is far from exhaustive when it comes to water bodies. That being said, I don't see a big problem leaving them in for now, but if you're up for finding/making better alternatives, you're right, the standard would not be high 😄, so please be my guest!
- For all the template-based maps, notably water bodies, I don't reckon they're worth replacing for now, especially since their licences are most likely okay, as you said. They can be dealt with as part of issue #1, as the most important aspect, in my opinion, is consistency.

So, I figure the resolution for this specific issue is to:

1. Replace a few maps with better-licenced, more up-to-date and better-looking versions, as discussed above.
1. Create a `sources.csv` file listing all images, their sources, licences and modifications.
1. Mention `sources.csv` in `LICENSE.md` and remove the lists of image licences from it.

Please let me know what you're happy to take on (no pressure 😄), so we can coordinate the work. Thanks again!!!

**Comment by aplaice** [comment]
> Are you up to get this started right away, at least with the licences you added in your PR #103,

Yes, I can do that tomorrow.

> About the three seas you mention that are most likely not under a permissive licence, I'd be tempted to remove them from the deck altogether. to be honest.. After all, the deck is far from exhaustive when it comes to water bodies. That being said, I don't see a big problem leaving them in for now, but if you're up for finding/making better alternatives, you're right, the standard would not be high smile, so please be my guest!

I've been playing around with making nicer maps for the Dead Sea and the Sea of Galilee. (Using the SVG maps from Wikimedia it's surprisingly fun...) I also have some ideas for the Norwegian Sea, so I think all three could be left in for the moment. Removing material feels a shame.

> 1. Replace a few maps with better-licenced, more up-to-date and better-looking versions, as discussed above.

Yeah, I'll definitely do that.

> 2. Create a sources.csv file listing all images, their sources, licences and modifications.

I'm not sure if I'm up for doing that for all the images, in the immediate future, but I can definitely do it for the "newly identified" ones (as mentioned above) and the current "exceptions". The public domain flags and the standard 16:9 maps, which are currently referred to as groups and which make up the vast majority of the images, could probably be filled in gradually, over time. I'd be happy to do some of these, but probably not all of them.

(Regarding public domain images, no attribution is of course needed, but I think that, time allowing, having sources for them might be useful to avoid confusion and to potentially facilitate upgrades if new versions are released on Wikimedia.)

Thank you again for the deck! I just felt like contributing something back.

**Comment by axelboc** [comment]
Great, thanks, just do what you can and I'll fill up the rest! 😉

**Comment by axelboc** [comment]
Well, that's `sources.csv` filled in! I'll polish off `LICENCES.md` tonight and we can close this issue at last!

**Comment by aplaice** [comment]
I've added the EU flag whose weird license might have tripped your Node script.

> and we can close this issue at last!

Hooray!
