### ISSUE TITLE
On the capital of Palau

### ISSUE THREAD

**Issue by ruricolist** [axelboc/anki-ultimate-geography#20]
I wanted to look up how to pronounce Ngerulmud, but I’ve fallen into a sort of rabbit hole. It turns out that, for small island nations, there is sometimes an ambiguity in exactly what should be considered the capital.

The problem is that the legal capital may be a settlement that does not correspond to any administrative division. E.g. the legal capital of American Samoa is [Fagatogo][] -- it says so in their [constitution][] -- but most references, including the existing card, say Pago Pago, because that's the smallest administrative unit that contains the capital.

As far as I can tell, all the existing cards for countries with this problem – at least American Samoa, Kiribati, and the Northern Mariana Islands – use the smallest administrative division. The card for Palau is the only exception; it uses the name of the settlement (Ngerulmud) instead of the name of the administrative division (Melekeok).

I’d like to suggest that an *ultimate* geography deck should have a policy – administrative division or settlement name – and apply it consistently. In practical terms that would mean either preferring administrative divisions, and changing the card for the capital of Palau, or settling on settlement names, and changing the cards (at least) for American Samoa, Kiribati, and the Northern Mariana Islands.

[Fagatogo]: https://en.wikipedia.org/wiki/Fagatogo
[constitution]: http://www.asbar.org/index.php?option=com_content&view=article&id=1961&Itemid=177#sec509

**Comment by axelboc** [comment]
The complexity of what defines a capital is indeed really interesting... Seats of power, constitution, conflicts, even natural disasters (e.g. [Montserrat](https://en.wikipedia.org/wiki/Montserrat))...

When it comes to capitals, **the deck's source of truth is Wikipedia**. The encyclopaedia has a thorough definition of what a capital is, and complex cases are always well explained.

In the case of American Samoa, my naive guess is that it comes down to widely accepted usage; after all, Fagatogo is but a village in the urban agglomeration of Pago Pago. Wikipedia does mention that the term [_seat of government_](https://en.wikipedia.org/wiki/Seat_of_government) is not synonymous with _capital_, and that the two differ in a few countries including the Netherlands, so this is not an isolated case.

I was just thinking that we could mention Fagatogo in the _capital info_ field, but I don't even think we should simply because Wikipedia does not list it at all as a capital, whereas when other countries' capitals are contentious, like for Montserrat, it does list them all clearly.
