### ISSUE TITLE
Review country info for Kaliningrad Oblast

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#208]
See https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-583866082 (item no 26).

**Comment by aplaice** [comment]
I'm hijacking this issue to avoid opening yet another issue about Kaliningrad Oblast (and because the Norwegian translation might be affected by this).

1. Should the country info (in English, French and Spanish) be using the term "State" (and equivalent — I think that "état" and "estado" have similar connotations to "state")? 

    The term "state" has connotations of independence or autonomy within a federal country. Russia is a federation, but Kaliningrad Oblast is not autonomous, and the "Oblast" is probably the least (nominally*) self-governing of the [Russian types of subdivisions](https://en.wikipedia.org/wiki/Federal_subjects_of_Russia#Types).

    \* one could argue to what extent any of these entities have real autonomy...

    [Oblasts of Russia](https://en.wikipedia.org/wiki/Oblasts_of_Russia) suggests translating Oblast as "province" or "region". [Federal subjects of Russia](https://en.wikipedia.org/wiki/Federal_subjects_of_Russia#Terminology) discusses what is the best collective English term for al the subdivisions of Russia (Oblast, Republic, Okrug etc.) and mentions "subject" and "constituent entity" (the latter is used on what appears to be [the Russian constitution on an official site of the Russian government](http://archive.government.ru/eng/gov/base/54.html)). constitution.ru (it's linked by Wikipedia, but I haven't been able to confirm either way whether it's unofficial) uses ["Region" as the translation for Oblast.](http://www.constitution.ru/en/10003000-04.htm)

     In the light of this, I'd suggest changing the phrasing to "Oblast (region) of the Russian Federation.", since "subject" is a bit ambiguous without wider context and "constituent entity" is rather unwieldy. I personally prefer "Oblast (region)" to "Region (oblast)" ("Oblast" is the official term and "region" is the parenthesised explanation) but either makes sense.

2. Should the French switch to the full "de la fédération de Russie" in the country info just like the remaining existing translations? (Currently, it's just "État (oblast) de Russie.") Emphasising that Russia is a federation might make sense. 

    OTOH given that Kaliningrad isn't actually autonomous, the federal status of Russia might not actually be worth emphasising, especially since we don't usually use the full name of the "parent" country in the country info, unless the full name refers to a slightly different entity than the short name (cf. Netherlands and the Kingdom of the Netherlands) which isn't the case for Russia.

    In any case, it should probably be consistent...

3. Should the German also include a parenthesised explanation of what an oblast is in the country info? (Currently, it's "Oblast der Russischen Föderation.")

Overall, my suggestions for the Country info would be:

Oblast (region) of the Russian Federation.
Oblast (Gebiet) der Russischen Föderation. (see [German Wikipedia](https://de.wikipedia.org/wiki/Oblast_Kaliningrad))
Óblast (región) de la Federación de Rusia. ([Spanish Wikipedia](https://es.wikipedia.org/wiki/%C3%93blast_de_Kaliningrado)
Oblast (région) de la fédération de Russie. ([French Wikipedia](https://fr.wikipedia.org/wiki/Oblast_de_Kaliningrad)) (I'm not 100% sure about the best capitalisation of "fédération" ([see this note](https://fr.wikipedia.org/wiki/Russie#cite_note-5).))
Oblast (distrikt) i den russiske føderasjon. (https://no.wikipedia.org/wiki/Kaliningrad_oblast)

**Comment by axelboc** [comment]
I'd down with all that!

Let's follow Wikipedia and keep "fédération" in lower case, I reckon. This means we need to fix "royaume des Pays-Bas" and "royaume du Danemark" in a few places, though.

**Comment by josealberto4444** [comment]
I agree with the proposal for Spanish country info. =)

**Comment by Vages** [comment]
Good idea! In Norwegian, I would go for «Oblast (distrikt) i Russland», which translates verbatim to «Oblast (region) of Russia». I'm not sure if going less formal with the name is against the spirit of the deck, but I like it better this way.

Should I assign myself to the issue and fix it?

**Comment by aplaice** [comment]
> I'm not sure if going less formal with the name is against the spirit of the deck, but I like it better this way.

I don't think there any particular rule against it, and anyway, you're the only person who can judge the nuances of what sounds better.

> Should I assign myself to the issue and fix it?

If you can, that would be great!

<hr/>

Also, thanks for checking the translations in all the other issues!

**Comment by Erim24** [comment]
I agree that including some additional info could be beneficial. I don't think that many German speaking people know what an Oblast is.
In that sense, I would even take an information from the Wikipedia site about [Oblast](https://de.wikipedia.org/wiki/Oblast) in general and add the following:
`Oblast (administratives Gebiet) der Russischen Föderation.`

**Comment by axelboc** [comment]
I quite like @Erim24's idea. Should we use the term `administrative` in the other languages too?

```
Oblast (administrative region) of the Russian Federation.
Oblast (administratives Gebiet) der Russischen Föderation.
Óblast (región Administrativa) de la Federación de Rusia.
Oblast (région administrative) de la fédération de Russie.
Oblast (administrativ distrikt) i den russiske føderasjon.
```

---

@Vages, happy to take this one over, if you haven't already started on it?

**Comment by aplaice** [comment]
> [ES] Óblast (región Administrativa) de la Federación de Rusia.

There's a capitalisation typo here (s/Administrativa/administrativa/", probably from looking at the German. :)

> [NB] Oblast (administrativ distrikt) i den russiske føderasjon.

I think it should be "administrativt distrikt" (as "distrikt" is neuter ??). Also, should we use "Russland", as suggested?

**Comment by axelboc** [comment]
All fixed, thanks!

> I think it should be "administrativt distrikt" (as "distrikt" is neuter ??)

How do you know these things !? 😮 👏 😄

**Comment by aplaice** [comment]
I had studied a bit of Swedish (via Duolingo, so it's rather poor) and tried applying the knowledge to Norwegian...
