### ISSUE TITLE
Missing British Overseas Territories

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#221]
Came across [Akrotiri and Dhekelia](https://en.wikipedia.org/wiki/Akrotiri_and_Dhekelia) while looking something up. Any reason this territory of Britain is not included? It has a capital "Episkopi".

Then looking at the wiki page for [British Overseas Territories](https://en.wikipedia.org/wiki/British_Overseas_Territories) I saw that we also do not have:

- [Tristan da Cunha](https://en.wikipedia.org/wiki/Tristan_da_Cunha) (Capital: "Edinburgh of the Seven Seas" :sunglasses:)
- [South Georgia and the South Sandwich Islands](https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands) (Capital: King Edward Point)

Every other British Overseas Territory seems to be accounted for :+1: 

###### Tbh I want Tristan da Cunha in the deck just because "Edinburgh of the Seven Seas" is fucking badass :laughing:

**Comment by aplaice** [comment]
I think that in general we have far too many tiny, underpopulated overseas territories, and perhaps we're overdue for a cull (see #137).

> Then looking at the wiki page for British Overseas Territories I saw that we also do not have:

What about [Ascension Island](https://en.wikipedia.org/wiki/Ascension_Island)? (population 806)

Also, what about the remaining French collectivities...

* [Wallis and Futuna](https://en.wikipedia.org/wiki/Wallis_and_Futuna) (population 11,558)
* [Saint Pierre and Miquelon](https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon) (population 6,008)

...and the various (uninhabited) Antarctic territories...

For comparison, the populations of Akrotiri and Dhekelia, Tristan da Cunha and South Georgia and the South Sandwich Islands, are respectively:

* Akrotiri and Dhekelia: 15,700 (half of which is military personnel and their families)
* Tristan da Cunha: 246
* South Georgia and the South Sandwich Islands: 0 permanent, 99 non-permanent...

I'd vote for *possibly* including Akrotiri and Dhekelia, as having the largest population and some political significance/interest (e.g. the UK was offering to give up part of the base, as a sweetener for the Annan plan for the reunification of Cyprus in 2004), and ignoring the rest (sorry Edinburgh of the Seven Seas!), though that's just my arbitrary opinion.

**Comment by ohare93** [comment]
Agreed that we have too many tiny useless rocks :sweat_smile: Just wanted to bring it up so that a decision can be made.

Akrotiri and Dhekelia is definitely the most deserving, agreed :+1: (No Edinburgh of the Seven Seas! :sob:)

**Comment by axelboc** [comment]
I've been dreading getting back into #137...

This is a topic that's been bothering me since the very early days of the deck -- see issue #11. Back then, I had made the arbitrary decision to only include notes that were "reasonably easy to memorise"... How vague and subjective was that for a criteria! 😂 

I feel like we made some progress in #137, but I don't have the time to champion this work myself. 

I have to say that _Akrotiri and Dhekelia_, and other military bases like the _British Indian Ocean Territory_, do not seem very worthy of inclusion... I'm sure other countries like China or Russia have similar bases that we'd never even consider adding. I think #137 should really aim at making the deck less "western".

**Comment by aplaice** [comment]
> I'm sure other countries like China or Russia have similar bases that we'd never even consider adding.

I don't think that they do. They do have military bases which they lease off from other countries, but none where they have actual sovereignty over the territory. The USA/UK/France also have many such "leased" bases, but we're not including any of them either.

<overly_long_digression>

Also, South Ossetia, Abkhazia and to some extent Transnistria are in a way the Russian "equivalents" of overseas territories (obviously they're not overseas, but Russia has historically been more into land-based expansion), as they're countries that Russia has created and/or supported with varying amounts of military force, and which have Russian puppet governments. South Ossetia and Abkhazia haven't been annexed, mainly for appearance's sake (at least until the invasion of Crimea, Russia didn't want to appear *too* brazen).

China doesn't have overseas territories since until the ~1970s it was in centuries-long crisis and since then its rise has been mostly peaceful.

The only countries that *could* have overseas territories are those that were industrialised before 1945 (since 1945 actual territorial acquisitions (as opposed to installing ideologically-aligned or puppet governments etc.) have *mostly* fallen "out of fashion") and that didn't lose (or didn't participate in) the two world wars and the Cold War.

Some countries do have enclaves within other countries (e.g. [Bangladesh in India](https://en.wikipedia.org/wiki/Dahagram%E2%80%93Angarpota)), but they're usually not far overseas.

</overly_long_digression>

I fully agree, though, that, arguably, we have far too many small dependent territories and regions, too many of which are western.

**Comment by axelboc** [comment]
Perhaps we should take another look at this page, which was my reference when I initially cleaned the deck: https://en.wikipedia.org/wiki/List_of_sovereign_states. The last column is where contentiousness lies. It shows how many autonomous territories exist, even in "non-western" countries. Pakistan controls two territories in Kashmir, China has five autonomous regions, including Tibet, etc. Doesn't help with deciding what goes in the deck, though...

**Comment by GrimPixel** [comment]
In my opinion, we should combine
https://en.wikipedia.org/wiki/List_of_sovereign_states
https://en.wikipedia.org/wiki/Dependent_territory
and remove other political entities.

**Comment by axelboc** [comment]
Ooh, the [Dependent territory](https://en.wikipedia.org/wiki/Dependent_territory) article is interesting! How about going even further and only keeping [inhabited dependent territories](https://en.wikipedia.org/wiki/Dependent_territory#Overview_of_inhabited_dependent_territories)?

It would feel weird to have to remove the [French overseas regions](https://en.wikipedia.org/wiki/Overseas_department_and_region) (French Guyana, Martinique, Guadeloupe, etc.) as well as the three municipalities of the Kingdom of the Netherlands (Bonaire, Saba and Sint Eustatius), though... But at least we'd have a well-defined list to work with.

**Comment by ohare93** [comment]
>It would feel weird to have to remove the French overseas regions (French Guyana, Martinique, Guadeloupe, etc.) as well as the three municipalities of the Kingdom of the Netherlands (Bonaire, Saba and Sint Eustatius), though... But at least we'd have a well-defined list to work with.

:scream:

**Comment by aplaice** [comment]
A well-defined list is nice, but a situation where we keep Saint Barthélemy and add Saint Pierre and Miquelon, or Akrotiri and Dhekelia, but remove French Guyana (!!), Martinique and Guadeloupe feels *extremely* weird...

**Comment by ohare93** [comment]
Wait a minute, this would qualify Tristan da Cunha! :100: :+1: Anything that get Edinburgh of the Seven Seas in the deck has my full backing! :muscle: :laughing:

**Comment by aplaice** [comment]
> Wait a minute, this would qualify Tristan da Cunha! 100 +1 Anything that get Edinburgh of the Seven Seas in the deck has my full backing! muscle laughing

I actually thought about that, but unfortunately it'd only qualify the entity ["Saint Helena, Ascension and Tristan da Cunha"](https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha) (capital Jamestown). :p

**Comment by axelboc** [comment]
>😱

Sorry, I wasn't clear at all 😄 

I was trying to say that this list would constitute a good base for our future guidelines ... but that the final guidelines would need to include additional lists, like French overseas regions -- because I'd feel too weird if they didn't.

This list of inhabited dependent territories feels like a nice complement to the list of sovereign states in terms of political geography. It would tidy things up a bit by allowing us to officially remove uninhabited territories and other random places like _Mount Athos_, while requiring us to add only a handful of new territories (five or six, I believe). A small price to pay for more clarity, IMO. Also, the list being exhaustive, we'd be able to tag the notes with `UG::Dependent_territory`.

**Comment by axelboc** [comment]
Here's a little audit:

- Out of the [40 inhabited dependent territories](https://en.wikipedia.org/wiki/Dependent_territory#Overview_of_inhabited_dependent_territories) listed on Wikipedia, 36 are already in the deck.
- The four that are not are: _Akrotiri and Dhekelia_, _Saint Pierre and Miquelon_, _Svalbard_, _Wallis and Futuna_.
- Interestingly, Wikipedia lists the _Cook Islands_ and _Niue_ as both [sovereign states](https://en.wikipedia.org/wiki/List_of_sovereign_states#List_of_states) and dependent territories.
- The _British Indian Ocean Territory_ is the only uninhabited dependent territory currently in the deck.
- The deck contains an additional 34 notes that are neither sovereign states nor dependent territories:
  - 5 French overseas regions/departments: _French Guiana_, _Guadeloupe_, _Martinique_, _Mayotte_, _Réunion_
  - 4 constituent countries of the United Kingdom: _England_, _Wales_, _Scotland_, _Northern Ireland_
  - 3 autonomous communities of Spain: _Canary Islands_, _Ceuta_, _Melilla_
  - 3 special municipalities of the Netherlands: _Bonaire_, _Saba_, _Sint Eustatius_
  - 3 subregions of Oceania: _Melanesia_, _Micronesia_, _Polynesia_
  - 2 autonomous regions of Portugal: _Azores_, _Madeira_
  - 2 regions and islands of Italy: _Sardinia_, _Sicily_
  - 2 islands of Indonesia: _Sumatra_, _Java_
  - 10 other unique entities: _Corsica_, _Bali_, _Easter Island_, _Galápagos Islands_, _Kaliningrad Oblast_, _Mount Athos_, _Zanzibar_,  _Scandinavia_, _Balkan Peninsula_, _European Union_.

**Comment by aplaice** [comment]
I'd move Bali into the Indonesia category even if it's a bit different as it's also a province (unlike Sumatra and Java, each of which is made up of several provinces, since they're much larger).

**Comment by axelboc** [comment]
It's delicate, since the deck includes Bali more as a political entity than an island (the note has a capital and a flag). But you're right, I've updated the groups. 👍
