### ISSUE TITLE
Sort flag similarities by importance

### ISSUE THREAD

**Issue by josealberto4444** [axelboc/anki-ultimate-geography#225]
As I might have some doubts (and for remembering), I will open this issue. I plan to do it myself, but I don't know how to assign the issue to my user (I don't usually use GitHub, to be honest).

**Comment by josealberto4444** [comment]
I've changed Nicaragua/El Salvador to `different coat of arms, slightly lighter/darker blue`, as the latter difference is negligible (ΔE = 15.3). However, I wonder if we should even say that, as there is already a minor difference, following the guidelines:

> Critical, major and minor differences should be listed in the Flag similarity field. Negligible differences should be listed only when relevant, notably when two flags share nothing but negligible differences.

If you think it's relevant, I have no problem in keeping it.

**Comment by aplaice** [comment]
Given that the coat of arms are pretty similar (both are based on a triangular motif, with some details added), it might, *perhaps*, be worth keeping the colour difference.

Technically, it wouldn't be against the guidelines, since those give the case with only negligible differences as the central example, but not the only possibility. Also, one could argue that there should be an additional negligible difference category:

    subtly different decoration of same type in same position (e.g. different symbol, different coat of arms)

(This opens up the can of worms of what a subtle difference is, but then the distinction in subtle and not subtle geometry differences also isn't rigorously defined.)

I'm not wholly convinced myself, though...

**Comment by axelboc** [comment]
> By the way, it is the only place where the appropriate sorting was not enforced. The differences were already sorted everywhere else.

Awesome, thanks for having a look!

The difference in coat of arms in this case is indeed quite negligible, so let's keep listing the negligible colour difference. The word _should_ means the guidelines technically still apply, even without the addition of a negligible difference category.
