### ISSUE TITLE
Add more subregion tags

### ISSUE THREAD

**Issue by GrimPixel** [axelboc/anki-ultimate-geography#244]
As we can see, a lot of countries don't have subregion tags. I have done this part in my personal project:
https://ethercalc.org/GrimPixel-list-of-countries

**Comment by axelboc** [comment]
From #242, I take it you'd like to have tags for every subregion in the [United Nations geoscheme](https://en.wikipedia.org/wiki/United_Nations_geoscheme)?

I feel like some of the subregions in this geoscheme, like _Southern Africa_ or _Eastern Asia_, include too few countries for a tag to really be useful. Some of the tags in the deck are already quite small: 10 notes for `UG::North+Central_America`, 13 for `UG::Southeast_Asia`, etc. Creating a filtered deck with fewer notes than that doesn't seem worthwhile (to me, anyway).

I do agree that some parts of the world, especially Africa, could benefit from a couple of extra tags, though. Perhaps we should combine some of the subregions (e.g. Western and Northern Africa) or find an alternate geoscheme?

**Comment by GrimPixel** [comment]
Having few notes to include in a tag doesn't means the tag is not helpful. We need to make tag precise and complete. If people think a tag contains too few notes, they just need to select multiple tags.

**Comment by axelboc** [comment]
If users end up having to always select multiple tags then the deck becomes a little less easy to use. Sure, smaller tags bring more flexibility, but does this flexibility really matter? Wouldn't people always combine the same tags anyway (e.g. Southern, Middle and Eastern Africa)?

**Comment by GrimPixel** [comment]
Learning several subregions of Africa is easier than learning the whole Africa. Same for others.
https://blog.rescuetime.com/why-you-should-be-setting-smaller-goals/

**Comment by axelboc** [comment]
See my earlier comment:

> I do agree that some parts of the world, especially Africa, could benefit from a couple of extra tags, though.

I'm only arguing that the subregions in the UN geoscheme are too small and that we should combine them. I think that splitting Africa into two subregions would suffice, for instance.

**Comment by GrimPixel** [comment]
If subregions tags are merged, how do people know where a country actually belongs to? They just know that it belongs to one of several subregions.
A subregion does not have many countries, and it is still a subregion. There are already continent tags if people want to find more entries at one time. There is no need to create some combination here.
“Too small” is not convincing when it comes to geography.

**Comment by axelboc** [comment]
> [...] how do people know where a country actually belongs to?

What you're talking about is learning to associate each country with its subregion. For instance, you see _Zimbabwe_ and you have to guess _Southern Africa_, or you see _Southern Africa_ and you have to list all the countries it contains (expert level 😄).

I don't think tags are the answer. If you create a filtered deck for _Southern Africa_, you learn facts about the countries it contains -- you don't train your brain to associate these countries with _Southern Africa_.

It would make more sense to add a new _Subregion_ field and a new _Country - Subregion_ template, or even to just create a completely separate deck.

**Comment by GrimPixel** [comment]
Talking about fields, I'd like to say that seas and oceans can be put into a new deck because the note type doesn't fit them (calling a river as a country). They can be created into a separate deck. In fact, it can be a huge deck for waters: https://www.memrise.com/course/28784/rivers-lakes-and-seas/

Adding the new field for subregions is a good solution, I think.

**Comment by axelboc** [comment]
Does anyone else have an opinion about whether or not to add tags for subregions as per the [United Nations geoscheme](https://en.wikipedia.org/wiki/United_Nations_geoscheme)?

For reference, the deck already contains the following subregion tags: `UG::North+Central_America`, `UG::South_America`, `UG::Caribbean`, `UG::Middle_East`, `UG::Southeast_Asia`. There's also `UG::European_Union` and `UG::Mediterranean`, but not sure they are concerned by the problem at hand.

Here are some options:

1. Add UN subregion tags, removing or replacing existing subregion tags as needed.
2. Cover the entire world with subregion tags by combining UN subregion tags (so that each tag is big enough but not too big).
3. Add a few more subregion tags to cover parts of the world that don't have any, like Africa.
4. Rename some of the existing subregion tags to better match the UN geoscheme.
5. Status quo, don't change anything.

---

As per my previous comments, my preference goes to **option 3**, but I don't mind options 2, 4 and 5 as well.

My main problem with option 1 is that the UN geoscheme defines no less than 22 regions, and I don't think that adding 22 tags is a good idea:
- It would clutter the sidebar of the Anki Browser (for people that don't have the extension to group tags into folders).
- It would make finding a specific tag more difficult (especially the note type and continent tags).
- I really don't see the point of having a tag with two notes in it (i.e. _Australia and New Zealand), or more generally, less than 10.

**Comment by aplaice** [comment]
I fully agree with **option 3**.

**1** would indeed add too many tags.

The UN geoschemes are sometimes rather unnatural or lumped-together\*. Their main value over more "natural" subdivisions (with which they often, but, as noted, not always, coincide), is that they [partition](https://en.wikipedia.org/wiki/Partition_of_a_set) the countries of the world, allowing one to easily order one's studying by geographical area. However, ordering study by region is probably not the only purpose of the regional tags\**, and for the other purposes I can think of, they're not very useful (where they diverge from the "natural" subdivisions). Hence, I'd vote against **4**.

\* For example, relatively few people use the term "Western Asia", instead using the mostly overlapping "Middle East". "Southern Asia" is virtually never used; "South Asia" is, but unlike the UN geoscheme's "Southern Asia" it doesn't include Iran. I'm far less confident here, but I think that few people use "Middle Africa" — there's "Central Africa", but it's not *necessarily* completely coterminous.

\** I've never actually used any of the tags, so I'm not sure what people use the "regional" tags for, but I'd guess that it's something like:

<details>

A. They live in a specific region (and only want to learn about countries there).

B. Conversely, they feel that they have very little knowledge about a given region (that's far away from them and that they hear very little about) and want to learn about it.

C. They have a test about a given region.

D. They're just fascinated by the given area.

</details>

To the extent that the UN geoscheme areas are unnatural, combining several of them together is unlikely to make the grouping less artificial, so **2** is also probably not great.

Africa does have too few tags, so I'd avoid **5** as well.

<hr/>

## Tags to add

### Africa

IMO [**West Africa**](https://en.wikipedia.org/wiki/West_Africa) and [**East Africa**](https://en.wikipedia.org/wiki/East_Africa) would definitely make sense as tags — they each have a well-defined territory, contain a large number of states (16 and 20 respectively — more than either `South_America` or `North+Central_America`) and have some sort of shared historical and cultural heritage.

[North Africa](https://en.wikipedia.org/wiki/North_Africa) would have made sense, as it's very well-defined, but it contains only 6 sovereign countries. Perhaps we could have a Middle_East+North_Africa tag or a [Greater Middle East](https://en.wikipedia.org/wiki/Greater_Middle_East) one? (All these countries do have considerable common heritage, so it wouldn't be a completely artificial grouping.) (It's not necessarily problematic for a country not to have a regional tag other than the continental one (see below), though since Sudan is a North African country, but not a Mediterranean one, unfortunately `tag:UG::Africa tag:UG::Mediterranean`, in line with what I suggest later, wouldn't be a sufficient replacement.)

[Central Africa](https://en.wikipedia.org/wiki/Central_Africa) also probably doesn't make sense. There's some debate on its limits (are Angola, São Tomé and Principe, Rwanda and Burundi part of it? (all of these are part of the [Economic Community of Central African States](https://en.wikipedia.org/wiki/Economic_Community_of_Central_African_States#Economic_and_Monetary_Community_of_Central_Africa), but the latter two are also part of East Africa...)) and even at its most extensive (incl. Rwanda and Burundi) it'd only contain 11 countries.

[Southern Africa](https://en.wikipedia.org/wiki/Southern_Africa) is even more iffy as it has multiple definitions and even at its most extensive (overlapping both Central and East Africa) has only 16 countries. With the non-overlapping definition it has only 5...

We could combine Southern and Central Africa, but a grouping containing both South Africa and Chad, but not, say, Kenya would be very weird...

#### My tentative recommendations:

* West Africa
* East Africa
* (? perhaps) Middle East+North Africa 
* (probably not) Southern Africa + Central Africa

Alternatively, we could have the two super-groupings West+Central Africa and East+Southern Africa, but they'd feel slightly unnatural.

### Elsewhere

Central Asia and South Asia both contain far too few countries, but joining them would also be nonsensical.

A crazy (not really serious) idea, inspired by the Mediterranean tag: the [Pacific Rim](https://en.wikipedia.org/wiki/Pacific_Rim).

## Grouping countries by region, for ordering one's study

There doesn't have to be an exhaustive set of tags that uniquely cover all the countries, in order to be able to "partition" the countries. For instance, with the existing tags, you can already geographically split Europe with `tag:UG::Europe tag:UG::Mediterranean` and `tag:UG::Europe -tag:UG::Mediterranean`. For Asia, you can have `tag:UG::Asia tag:UG::Middle_East`, `tag:UG::Asia tag:UG::Southeast_Asia` and (the admittedly excessively large) `tag:UG::Asia -tag:UG::Middle_East -tag:UG::Southeast_Asia`.

**Comment by axelboc** [comment]
> There doesn't have to be an exhaustive set of tags that uniquely cover all the countries, in order to be able to "partition" the countries.

I totally agree. As long as there's a way to remove a big chunk of countries from a continent, I think we're good.

For this reason, I think adding `UG::West_Africa` and `UG::East_Africa` (and only these two) makes the most sense. By filtering them out of `UG::Africa`, we end up with an estimated 26 notes ... just like `tag:UG::Asia -tag:UG::Middle_East -tag:UG::Southeast_Asia`! Given that `UG::Caribbean` contains 31 notes, I think that's a good number.

... This makes me wonder now whether tags `UG::South_America` and soon-to-be-renamed `UG::Northern+Central_America` are worth having at all, since they contain 25 notes together. 🤔 Perhaps we could just remove the latter since it makes the least sense as per naming discussions in #295 .

**Comment by axelboc** [comment]
Closing this now as the agreed changes are covered by separate issues. 👍
