### ISSUE TITLE
Missing Media File in v3.3 Release: ug-map-south_america-nobox.png

### ISSUE THREAD

**Issue by ukanuk** [axelboc/anki-ultimate-geography#283]
Looks like during #274 commit c5d5f96, renaming `ug-map-south_america.png` was accidentally forgotten. Also, maybe it would be helpful to mention in the release notes that if upgrading, one should check media to delete old files?

![image](https://user-images.githubusercontent.com/59303202/79284869-dd6a3080-7ef6-11ea-8590-f90abf10e133.png)

**Comment by aplaice** [comment]
Oops, I hadn't caught that. :(

Thanks for fixing it!

Looking at the commit in question, it looks like South Africa's map was renamed instead of South America's. (That probably didn't come up during your media scan, since the note still refers to `ug-map-south_africa.png`, so `ug-map-south_africa-nobox.png` was not added to the apkg, while `ug-map-south_africa.png` was obviously still present in your media folder.)

**Comment by ukanuk** [comment]
@aplaice it's merged, thank you!

**Comment by axelboc** [comment]
Oops, thanks for that! I'll publish the fixed shared deck now.

**Comment by axelboc** [comment]
Done! I've updated the shared deck and the release note files. Let me know if something's not right.

**Comment by ukanuk** [comment]
I can't find the changes in the release notes, but downloading the latest asset and importing into a brand-new Anki profile, the "Check Media" command completes with no issues found.

Downloaded package:
[v3.3.1/Ultimate_Geography_v3.3.apkg](https://github.com/axelboc/anki-ultimate-geography/releases/download/v3.3.1/Ultimate_Geography_v3.3.apkg)
