### ISSUE TITLE
Add a test for checking media file use

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#285]
The purpose would be to avoid issues like #283.

It would check that `src/data.csv`, `src/media/` (and less importantly) `sources.csv` all contain/reference the same media files.

It might, perhaps, be best if this were part of `anki-dm` (so that the tests could be easily run locally, with an interface consistent with the existing "test" (`composer index`)), but that's not essential.

**Comment by ukanuk** [comment]
Agreed, although I'd think it's more important to have in `composer build` than in `composer index`. Since all my edits are modifying cards, templates, and media, I never need to run `composer index` and only ever use `composer build`. But it wouldn't hurt to have the check in both commands.

On the other hand, this check also involves parsing HTML looking for `<... ref="url">`, which may not be trivial. And if `anki-dm` is going away within the next year, it may not be worth the effort adding this feature until the tool of the future is determined.

**Comment by ohare93** [comment]
Implementing moving media in [Brain Brew](https://github.com/ohare93/brain-brew) right now :wink: Will fail in this exact scenario :+1:
