### ISSUE TITLE
Rename Artsakh to Republic of Artsakh

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#294]
The [new guidelines](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#country-field) require the name to match the title of the Wikipedia article: https://en.wikipedia.org/wiki/Republic_of_Artsakh.

The country info is already quite long, but we could add that it's commonly known as _Artsakh_.

**Comment by ukanuk** [comment]
Per Wikipedia policy I quoted in #181, the article title ought to be the most common name. Since *Artsakh* is neither the most common nor an official name, I don't see any reason to include it in UG country info.

Doubtless many people informally refer to the country with the shortened name, but this ought to be blindingly obvious enough that it would detract rather than add to the other stuff already in Country Info.
