### ISSUE TITLE
Add political entities with maps as per new inclusion rules

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#315]
The following political entities are to be added to the deck, **with maps only** (and country info as needed), as per the new [inclusion rules](https://github.com/axelboc/anki-ultimate-geography/pull/312) documented in [CONTRIBUTING.md](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#political-geography) and [political-entities.xlsx](https://github.com/axelboc/anki-ultimate-geography/blob/master/political-entities.xlsx):

- [x] [Wallis and Futuna](https://en.wikipedia.org/wiki/Wallis_and_Futuna)
- [x] [Akrotiri and Dhekelia](https://en.wikipedia.org/wiki/Akrotiri_and_Dhekelia)
- [x] [Svalbard](https://en.wikipedia.org/wiki/Svalbard) (i.e. the unincorporated area)
- [x] [Autonomous Region of Bougainville](https://en.wikipedia.org/wiki/Autonomous_Region_of_Bougainville)
- [ ] [Jeju Province](https://en.wikipedia.org/wiki/Jeju_Province)
- [x] [Hawaii](https://en.wikipedia.org/wiki/Hawaii) (i.e. the state)
- [x] [Alaska](https://en.wikipedia.org/wiki/Alaska)

For consistency, the locator maps should be centred on the territories and not highlight their parent countries.

**Comment by aplaice** [comment]
Looking at the existing maps on Wikimedia, there are some candidates for most of the new entities:

### Wallis and Futuna

#### https://commons.wikimedia.org/wiki/File:Wallis_and_Futuna_in_its_region.svg

![one](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Wallis_and_Futuna_in_its_region.svg/800px-Wallis_and_Futuna_in_its_region.svg.png)

I think that this one is just-about OK. (It's definitely not worse than any of our existing maps of the Pacific island countries — and due to the fact that it's close to Fiji (probably the most recognisable "landmark"), I think it'd be *relatively* easy to distinguish/learn.)

### Akrotiri and Dhekelia

#### https://commons.wikimedia.org/wiki/File:Akrotiri_and_Dhekelia_in_United_Kingdom.svg

![one](https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Akrotiri_and_Dhekelia_in_United_Kingdom.svg/800px-Akrotiri_and_Dhekelia_in_United_Kingdom.svg.png)

- It'd obviously need colour-adjustments, so that the UK was not highlighted. (Alll land needs to be `#FDFCEA`.)

- It *might* be better if Cyprus were centred, but 

    - I'm not convinced that it'd look better if the zoom box were moved to the side.

    - It is IMO useful to show the (no longer highlighted but still visible) UK, for context, since the "Country info" will be saying something to the effect of "Overseas territory of the United Kingdom.". (For the cases where the overseas territory is on a completely different side of the globe than its "parent country" this isn't practical, but here it just-about-works.)

#### https://commons.wikimedia.org/wiki/File:Akrotiri_and_Dhekelia_in_its_region_(de-facto).svg

![two](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Akrotiri_and_Dhekelia_in_its_region_%28de-facto%29.svg/800px-Akrotiri_and_Dhekelia_in_its_region_%28de-facto%29.svg.png)

I think it's far worse than the first option.

### Svalbard (i.e. the unincorporated area)

#### https://commons.wikimedia.org/wiki/File:Svalbard_in_its_region.svg

![one](https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Svalbard_in_its_region.svg/800px-Svalbard_in_its_region.svg.png)

I think it's perfect for our purposes!

### Autonomous Region of Bougainville

For reference (when creating a new map), there's [this](https://commons.wikimedia.org/wiki/File:Bougainville_in_Papua_New_Guinea_(special_marker).svg), but it's obviously unsuitable in itself.

### Jeju Province

Again purely for reference purposes, there's [this](https://commons.wikimedia.org/wiki/File:Jeju-teukbyeoljachi-do_in_South_Korea.svg).

### Hawaii (i.e. the state)

#### https://commons.wikimedia.org/wiki/File:Hawaii_in_its_region_(special_marker).svg

![one](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hawaii_in_its_region_%28special_marker%29.svg/800px-Hawaii_in_its_region_%28special_marker%29.svg.png)

I think it's suitable. I don't think there's any way of improving it. A zoom box wouldn't particularly help; adding more context would make things worse.

#### https://commons.wikimedia.org/wiki/File:Hawaii_in_its_region.svg

![two](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Hawaii_in_its_region.svg/800px-Hawaii_in_its_region.svg.png)

IMO it's clearly worse for our purposes than the version with the special marker.

### Alaska

**Comment by axelboc** [comment]
You're on fire! 😮 

Your suggestions are great. I feel like Hawaii and Svalbard are a bit too zoomed in and don't quite show enough context, but they'll do fine.
