### ISSUE TITLE
Northern Mariana Islands Flag outdated

### ISSUE THREAD

**Issue by HartBlanc** [axelboc/anki-ultimate-geography#317]
The [flag currently used for the Northern Mariana Islands](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-flag-northern_mariana_islands.svg) is outdated according to [Wikipedia](https://en.wikipedia.org/wiki/Flag_of_the_Northern_Mariana_Islands).

The one currently in the deck hasn't been used since the 1980s.

Would be good if this could be updated.

Old:
![image](https://user-images.githubusercontent.com/22865635/83945550-5608b180-a803-11ea-8055-92cee8a0035f.png)

New:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/1280px-Flag_of_the_Northern_Mariana_Islands.svg.png)

**Comment by aplaice** [comment]
Thanks for reporting this!

It seems that the flag was [recently updated on Wikimedia (after several back-and-forth reversions...)](https://en.wikipedia.org/wiki/File:Flag_of_the_Northern_Mariana_Islands.svg) from the version that we were using to the (now presumably correct) version.

FWIW the version that's been in the deck until now doesn't isn't quite the one from the 1980s — the shade of the [1980s one](https://en.wikipedia.org/wiki/File:Flag_of_the_Northern_Mariana_Islands_(1976%E2%80%931989).svg) was even lighter.

<hr/>

All of that said, due to the [updated inclusion rules for political entities](https://github.com/axelboc/anki-ultimate-geography/issues/306) (such as dependent territories like the Northern Mariana Islands), the flag of the Northern Mariana Islands won't be included in future versions of the AUG deck.

**Comment by HartBlanc** [comment]
Thanks for looking into it, the sources mentioned in the Wikimedia comments provide some evidence that it is the correct one, but I'm by no means an expert on the topic so can't say for sure.

Having had the updated inclusion issue brought to my attention it doesn't seem to be too important anyway. I guess I'll be forgetting all the miscellaneous knowledge I've accumulated about dependent territories that I was never going to use anyway 😅

**Comment by aplaice** [comment]
> I guess I'll be forgetting all the miscellaneous knowledge I've accumulated about dependent territories that I was never going to use anyway 

In principle, depending on how you update AUG you won't necessarily lose your existing cards, but yeah, the fact that most of this information regarding dependent territories isn't exactly very useful is why we're making the change.
