### ISSUE TITLE
Rename Australia (Oceania) to Oceania and add country info

### ISSUE THREAD

**Issue by emiham** [axelboc/anki-ultimate-geography#345]
Right now "Australia (Oceania)" is the only note with parentheses in the main entry. Should this not be in Country info? 

Additionally, are we sure Australia should be the primary name? From what I understand Oceania is the correct name for the region, as opposed to Australia the landmass, and so I feel like the note should be `Country: Oceania`, `Country info: Commonly referred to as Australia`. Maybe referring to it as Australia is more common, but if they're about equal I think it's better to be technically correct.

**Comment by aplaice** [comment]
Thanks for pointing this out!

I'm not quite sure how to best proceed here.

The region that is shown on the associated map is definitely Oceania, not Australia.

However, according to Wikipedia's articles on the [continents](https://en.wikipedia.org/wiki/Continent), [Oceania](https://en.wikipedia.org/wiki/Oceania) and [Australia (continent)](https://en.wikipedia.org/wiki/Australia_(continent)), Oceania isn't a continent, while Australia (i.e. Australia + New Guinea) is. (I guess that this is based on a geological definition of "continent", relying on the limits of the respective continental shelves etc.)

(Note though, that Encyclopedia Britannica, for instance, does not [seem to include the island of New Guinea in the Australian continent](https://www.britannica.com/place/Australia).)

Hence, if our justification for including "Australia/Oceania" is that we're including the continents from the "seven-continent model", then we should change the name to "Australia (continent)" (it can't be just "Australia" with the disambiguation in the "Country info" since we don't include the "Country info" in the Country->Map cards), in all languages, and adjust the map accordingly.

OTOH my opinion is that a division of the world's land such that some parts of it (e.g. New Zealand and the Pacific Islands) don't belong to any of the divisions is interesting from a geological point of view, but also pretty useless for most purposes. This is presumably why Wikipedia's own [Categorisation of Countries by Continent](https://en.wikipedia.org/wiki/Category:Countries_by_continent) has "Countries in Oceania‎" and not "Countries in Australia" as one of its subcategories. The category [SVG locator maps of continents](https://commons.wikimedia.org/wiki/Category:SVG_locator_maps_of_continents_(globe_location_map_scheme)) also includes Oceania and not Australia, as one of the seven continents (this is the reason why our map is of Aceania and not of Australia).

Interestingly, the GIF at the top of [Wikipedia's article on the continents](https://en.wikipedia.org/wiki/Continent), illustrating the [different continent models](https://en.wikipedia.org/wiki/File:Continental_models-Australia.gif), includes New Zealand in the continent named Australia...

<hr/>

AFAICT we have the following options:

1. Strictly follow the seven-continent model — rename the entity to Australia (continent), and adjust the map accordingly.

- possibly mention Oceania in the "Country info" (e.g. Australia is part of the geographic region Oceania, which also includes (...))???

2. Follow the seven-continent model, but using the "geographic region" Oceania instead of the "continent" Australia.

- possibly mention the continent Australia in the "Country info" (Oceania consists of the continent Australia, New Zealand and most of the islands in the Pacific. ) ???

- possibly also mention that the whole of Oceania is sometimes referred to as Australia (Sometimes the whole region is incorrectly described as being the continent Australia.) ???

- perhaps combined, rather long-windedly as:

> Oceania is strictly speaking not a continent. It consists of the continent Australia and most of the islands in the Pacific Ocean. The whole of Oceania is sometimes incorrectly referred to as Australia.

3. Keep the current state as perfectly reflecting the muddle of the situation.

4. Include both Australia and Oceania, as separate notes.

- possibly also add Eurasia etc.

I strongly lean towards **2**, but I recognise that this is an arbitrary preference. I'm also not sure what to include in the corresponding "Country info" without it becoming a dissertation...

<hr/>

"Glossary" (for fun)

Australia (continent) = (Australia (country) + New Guinea) OR just Australia (country) OR commonly but probably incorrectly\* all of Oceania; (is a continent)

\* to the extent that something can be incorrect with so many conflicting definitions. I'm judging it to be incorrect because the label seems to be sloppily used on maps to refer to the whole of Oceania even when the accompanying explanatory text explicitly states that Australia is a strict subset of Oceania.

Australasia = (Australia + New Guinea + New Zealand) OR (Australia + New Zealand); (is not a continent)

Oceania = Australia + Melanesia + Polynesia + Micronesia; (is not a continent)

**Comment by axelboc** [comment]
If we're talking about "continents", then `Australia (continent)` is the way to go. But this sucks because it feels pointless to have two cards named Australia, even if the map of the continent of Australia ends up including a few more islands. It seems much more interesting to learn that there is a world region called Oceania.

On top of that, the seven-continent model is really not that great because other parts of the world use different models and this deck is translated into languages that use those other models. That being said, the model still makes sense around the world, and I don't think covering other models by including Eurasia, for instance, is worth it.

All of this to say that I don't mind having **our own, loosely-defined seven-continent model** with Oceania rather than Australia. Thus, I do agree with @emiham about dropping the parens block "(Australia)", and I do agree with your second option, @aplaice about adding country info to clarify that we're not strictly talking about the continent (in English at least).

**Comment by axelboc** [comment]
For the country info, how about:

- [EN] World region covering the Australian continent and most of the islands in the Pacific Ocean.
- [FR] Région du monde englobant le continent australien et la plupart des îles de l'océan Pacifique.

**Comment by axelboc** [comment]
@Erim24, @josealberto4444, @Vages can you please review the following DeepL/Google Translate translations?

- [DE] Weltregion, die den australischen Kontinent und die meisten Inseln im Pazifischen Ozean umfasst.
- [ES] Región mundial que abarca el continente australiano y la mayoría de las islas del Océano Pacífico.
- [NB] Verdensregion som dekker det australske kontinentet og de fleste øyene i Stillehavet.

**Comment by Vages** [comment]
"Verdensregion som dekker" -> "Verdensdel som omfatter"

Otherwise great! I'm impressed with your/Google's translation.

**Comment by josealberto4444** [comment]
It is tecnically correct (except that "océano" is written in lowercase), but, from my point of view, does not make much sense. In Spanish, we don't talk about "continente australiano" ever, the continent is "Oceanía" and that's how it is taught in school (at least in Spain), so I'd say the following:

Continente que abarca Australia y la mayoría de islas del océano Pacífico.

or, if you want to be correct,

Continente que abarca Australia, Nueva Guinea y la mayoría de islas del océano Pacífico.

I suggest these two options because I had never heard about the Australian continent before translating this deck. In fact, when I translated it, I opted for translating "Australia (Oceania)" as "Oceanía" to avoid confusion between Spanish-speaking people.

---

On a different note, I'm sorry for not being active lately in this project.

You mentioned me some time ago (during summer) and I didn't even reply, and I am very sorry about that. My personal situation is difficult because after I defended my PhD thesis, I took some holidays that I really needed and, before finishing them, my father died. I am in the middle of a very difficult situation and I have tons of things to do. However, if you need something else from me (or you want me to pay attention to the things I skipped from this project), feel free to tell me or mention me again in the corresponding issues. I will take a look as soon as possible. =)

**Comment by axelboc** [comment]
You're right, Spanish Wikipedia does refer to Oceania as a continent. It also says that it includes the "continental platform of Australia" (_la plataforma continental de Australia_), which includes New Guinea. So how about:

- Continente que abarca la plataforma continental de Australia y la mayoría de islas del océano Pacífico.

---

Sorry to hear about your father. 😢 I hope your PhD thesis defense went well.

**Comment by josealberto4444** [comment]
Yes, perfect!

---

Thank you. And yes, it went well. =)

**Comment by Erim24** [comment]
> @Erim24, @josealberto4444, @Vages can you please review the following DeepL/Google Translate translations?
> 
>     * [DE] Weltregion, die den australischen Kontinent und die meisten Inseln im Pazifischen Ozean umfasst.
> 
>     * [ES] Región mundial que abarca el continente australiano y la mayoría de las islas del Océano Pacífico.
> 
>     * [NB] Verdensregion som dekker det australske kontinentet og de fleste øyene i Stillehavet.


I'm not sure if it is till necessary, but the German translation looks good to me.

I'm sorry for the long delay. I'll try to stick around more often again.

**Comment by axelboc** [comment]
No worries, welcome back! ☺️
