### ISSUE TITLE
Fresh start with 4.0 but opening message says 3.3

### ISSUE THREAD

**Issue by bigToadMan** [axelboc/anki-ultimate-geography#353]
I just downloaded and started fresh with " Ultimate_Geography_v4.0_EN.apkg". I was on 3.3 but deleted that deck (and card type) etc. 

Using the apkg version, onthe Windows latest 2.1.28 Anki. Click on the deck to study and it says "Ultimate Geography v3.3 features:" and says there is a tally of 321 notes but there is 304. 

Is this screen not updated or is the 4.0.apkg just 3.3 in disguise ?

**Comment by aplaice** [comment]
Thanks for reporting! 

The contents of the apkg (other than the description) is correct! (For instance, the Falkland islands now only have a Map->Country card.) The screen is just not updated.

(Looking at the CrowdAnki English non-extended zip and a random selection of the other zips, the deck information is up-to-date, so the issue is probably only confined to the apkg.)

**Comment by axelboc** [comment]
I recall a synchronisation issue with my first upload to AnkiWeb. I've re-downloaded the package and uploaded to the release. Let me know if it's fixed.

**Comment by bigToadMan** [comment]
I tried re-deleting, syncing, relunching Anki a couple times. 

Re-downloaded the same .apkg and now the opening message is a one-liner referring to the Shared Deck page. So I think that is the indented message, so I say its fixed. Thanks.
