### ISSUE TITLE
Canary Islands Capital missing full name

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#354]
[The Canary Islands](https://en.wikipedia.org/wiki/Canary_Islands) has two capitals `Santa Cruz de Tenerife` and `Las Palmas` though the latter is the shortened name instead of the full `Las Palmas de Gran Canaria`. Only came across the full name while scrolling on OpenStreetMaps, and then saw the [wiki entry agreed](https://en.wikipedia.org/wiki/Canary_Islands).

**Comment by aplaice** [comment]
According to the [guidelines](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#capital-field), the name of the capital that we use is the one used in the title of the corresponding article, not that listed in the infobox of the country, so I think that we should *probably* keep using the [short version](https://en.wikipedia.org/wiki/Las_Palmas) (and yes, Wikipedia does slightly inconsistently use the full name for [Santa Cruz](https://en.wikipedia.org/wiki/Santa_Cruz_de_Tenerife)\*).

\* Wikipedia probably uses the full name since there are other equally (or more) important [Santa Cruz](https://en.wikipedia.org/wiki/Santa_Cruz)s in the world. In contrast while there do exist other [Las Palmas](https://en.wikipedia.org/wiki/Las_Palmas_(disambiguation)), they seem smaller/less important than the one in the Canary Islands. Hence, *arguably* that makes `de Tenerife` a form of parenthetical portion of the name, which should be consequently removed, by the above guidelines... I'm not really convinced by my own argument, but the inconsistency between the two capitals is also non-ideal.

**Comment by axelboc** [comment]
Sorry @ohare93, the Canary Islands are no longer included with their capital and flag; only their map.
