### ISSUE TITLE
Improve Minor upgrade instructions

### ISSUE THREAD

**Issue by jasonwilliams** [axelboc/anki-ultimate-geography#398]
Thanks for maintaining this great deck. I'm trying to update from 4.0 to 4.1
When performing a minor upgrade i follow the instructions and use crowd anki.
But im not sure what should be ticked or not. 

In my screenshot is the default selection and the instructions on the right. 

<img width="1297" alt="Screenshot 2021-02-14 173709" src="https://user-images.githubusercontent.com/936006/107884173-535e7000-6eeb-11eb-87d5-394f15bab146.png">

Secondly there's no mention of a new deck being created. I have "ultimate georgaphy_2" what's going on here?
![image](https://user-images.githubusercontent.com/936006/107884584-ba7d2400-6eed-11eb-9ef4-2c3388b94911.png)

**Comment by aplaice** [comment]
Thanks for reaching out! We're aware of the deficiencies in the description and the duplicate deck creation issue. (This is what #391 was originally about until it turned out that there was also a similar, but more serious issue, for the non-English decks...)

>  But im not sure what should be ticked or not.

You don't need to tick anything, though you might want to tick the "do not move existing cards" box! If you do, then all the notes/cards that were already in your deck will be updated, but not moved from the deck they already were in.

> Secondly there's no mention of a new deck being created i have "ultimate georgaphy_2" should I delete the original one?

If you ticked the "do not move existing cards" box, then "Ultimate Geography" should contain 968 cards, while "Ultimate Geography_2" should contain 7 (new) cards. (You can check the number of cards in a deck by selecting the deck and clicking on "Stats" at the top (or pressing <kbd>t</kbd>).)

If you did not, then the _2 deck should contain 975 cards, while the original one 0 cards.

(If that's not right, then please complain here! :))

You can move all the cards into one deck, if you want (either one, though from the point of view of future upgrades, it's better if you move them into the "Ultimate Geography_2" deck, delete the original deck and then rename the "Ultimate Geography_2" deck "Ultimate Geography").

Sorry about the inconvenience and confusion!

**Comment by jasonwilliams** [comment]
Thank you for the great response.
I did have it ticked so now I have _2 with seven new cards in it. Do I move these 7 cards into the original deck?

**Comment by aplaice** [comment]
>  I did have it ticked so now I have _2 with seven new cards in it. Do I move these 7 cards into the original deck?

Yes. That's probably the most straightforward. 

(The advantage of doing it the other way round — i.e. moving the 968 cards into the _2 deck — is that in that case, if/when you upgraded from 4.1 to 4.2, then no duplicate decks would be created, (at least if we don't make any changes in the meantime...).

In case you're interested, here are the rather boring details why (and why the duplicate deck issue occurs at all, at least for the English deck): `CrowdAnki` uses `crowdanki_uuid`s to uniquely label and identify decks (so that `CrowdAnki` can "recognise" a deck irrespective of whether it's been renamed or if there are other decks of the same name). Unfortunately, when one imports a deck as an `.apkg`, Anki does not import the deck `crowdanki_uuid`. Hence, when one later imports/upgrades the deck with `CrowdAnki`, then `CrowdAnki` does not "recognise" the existing deck as corresponding to the one it's importing and creates a new one, this time with the deck `crowdanki_uuid`. (Notes are labelled/tracked with `guid`s, which _are_ imported in an `.apkg`, so luckily no duplicate _notes_ are created.) As a result, if you were to keep the _2 deck, rather than the original one, then the next time you upgraded, `CrowdAnki` would recognise the existing deck as corresponding to the deck it was importing and no new duplicate decks would be created.)

**Comment by jasonwilliams** [comment]
> You can move all the cards into one deck, if you want (either one, though from the point of view of future upgrades, it's better if you move them into the "Ultimate Geography_2" deck, delete the original deck and then rename the "Ultimate Geography_2" deck "Ultimate Geography").

Ok I did this thanks @aplaice 
This sort of info would go great in the documentation, its exactly what I was looking for
