### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Lidara** [axelboc/anki-ultimate-geography#52]
If I'd make a translation, would you include it? (German)

**Comment by axelboc** [comment]
Ooh this would be really useful, thank you! You'd have to be responsible for it in the long term, though, is that alright? This would include keeping the German deck up to date with the English deck and publishing it yourself on Anki. If it works for you, then I could make you a collaborator of the repo so you don't have to fork it -- would you like that?

**Comment by Lidara** [comment]
Cool! Yeah, that only makes sense. Do you think it is possible to make one deck with multiple languages, where you can switch between languages with an custom deck/study or would that make things to complicated for the user?

**Comment by axelboc** [comment]
Hmm good question. I see two ways of managing two languages in the same deck:

1. By adding more fields for the German translations.

The fields wouldn't show by default (i.e. a new Anki user would get the English deck out of the box), and users who want to study in German could edit the deck's card templates to show the German fields instead of the English ones and to rewrite the cues (e.g. "Country").

With this solution, the switch from on deck to the other is a bit complex but manageable (if well explained in the README). The real downside for me is that the new fields would add quite a bit of clutter to the notes, and it wouldn't be practical to add more translations in the future.

2. By duplicating every note in the deck (one for each language).

All the notes in German would be tagged as such, so it would be fairly easy to create a custom German-only deck. The downside, in my opinion, is that users would get both English and German cards by default so every user would have to customise the deck before being able to use it. I've mentioned this as a big no-no in the README: I think the deck should remain ready-to-use out of the box.

---

Can you think of another way? I'm no Anki expert, so there might very well be. But so far, it looks to me as if having two separate decks would be much simpler for users and a lot more maintainable for us (especially if more translations are added in the future).

The way I see it, the two decks would sit under two separate folders at the root of this repository. We could name the German deck something like _Ultimate Geography (DE)_. The folder would contain only the JSON file exported by CrowdAnki (no _media_ folder -- the package published on AnkiWeb, however, would of course contain the media files). Does it sound alright?

**Comment by Lidara** [comment]
Having it side by side with two decks seems to be the simplest, so let's do that.
I would translate just the cards and the tags, or would it also be necessary to translate the field names?

**Comment by axelboc** [comment]
Okay, I've just duplicated the English. It was more cumbersome than I thought, but I got there. I've attached the Anki package, so you can just open it and get started!

[Ultimate Geography (DE)_v0.zip](https://github.com/axelboc/anki-ultimate-geography/files/1857364/Ultimate.Geography.DE._v0.zip)

I've invited you to become a collaborator of this repo, so you should be able to create a branch and then a Pull Request whenever you're ready. When you export the deck with CrowdAnki, just make sure not to include the media files.

I don't think we need to translate the tags, I just don't see it being that useful. It might actually be useful to someone to have both English and German cards mapped to the same tag. Let's leave the field names as they are as well, since they're only visible to us. However, I've duplicated the note type (_Ultimate Geography (DE)_), so you can go ahead and edit the card templates it contains to translate the cues to German (e.g. "Country", "Capital", etc.) In summary, here are the bits that need to be translated:

- the content of the cards (of course :D),
- the cues in the note templates,
- the deck description.

When the time comes, we'll talk about releasing the deck. I'll also need to update the README and the decks' descriptions to list the available languages.

**Comment by Lidara** [comment]
I finally found some time today and translated about half the cards. I pushed it into a separate branch, I will continue working in de_wip until it is finished, then I'll look over the entire deck and when I'm happy I'll make a merge request for you to look over.

**Comment by alpha-strike** [comment]
I finished the translation and prepared it as json. If you enable uploads I can share it.

**Comment by axelboc** [comment]
Hi there! Hmm, you can open a Pull Request if you'd like?

**Comment by Lidara** [comment]
Thanks a lot for jumping in @alpha-strike!
