### ISSUE TITLE
Adding 'Note ID'

### ISSUE THREAD

**Issue by OtterBrah** [axelboc/anki-ultimate-geography#67]
Would you add a Note ID field and append it to all the cards so that it's possible to upgrade the deck in future iterations? I've seen it featured on medical school superdecks and it's helpful for upgrading cards with errata.

**Comment by axelboc** [comment]
Are you talking about the [Note ID add-on](https://ankiweb.net/shared/info/1672832404)? This add-on seems to be related to Anki's text import/export feature. We actually use a more complex add-on for managing import/export called [CrowdAnki](https://github.com/Stvad/CrowdAnki). This add-on does allow the deck to be upgraded (i.e. re-imported without loss of progress) in order to fix errata, add new notes, etc. If you look at [data.csv](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/data.csv), you'll see that each note indeed has a unique ID.

Why the question? Did you try to upgrade to v3.0? As mentioned in the [releases notes](https://github.com/axelboc/anki-ultimate-geography/releases/tag/v3.0), I'm afraid the upgrade is not possible for this specific version, because the deck is now managed by [Anki Deck Manager](https://github.com/OnkelTem/anki-dm). The change of structure meant that every note received a new ID. Hopefully this won't happen again in the future.

**Comment by OtterBrah** [comment]
Yes the suggestion was to prevent loss of scheduling information between versions. Having an appended note id external to CrowdAnki will let you have a manual Note ID you can control. I'm aware that each card can have its own internal ID, but having a unique first field will let you have more control over potential loss of scheduling information between versions if you ever move on from CrowdAnki. In other words, it future-proofs it in case something better than CrowdAnki rolls along.
